---
name: Parse-RPM-Spec
version: 0.02
author:
  - 'Dave Cross <dave@mag-sol.com>'
abstract: Perl extension to parse RPM spec files.
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  perl: 5.6.0
build_requires:
  Test::More: 0
provides:
  Parse::RPM::Spec:
    file: lib/Parse/RPM/Spec.pm
    version: 0.02
generated_by: Module::Build version 0.32
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
